---
- name: Delete IP from netbox
  netbox.netbox.netbox_ip_address:
    netbox_url: '{{ netbox_server }}'
    netbox_token: '{{ netbox_token }}'
    data:
      address: '{{ ip_to_delete }}'
    state: absent
