---
- name: Create a DNS record for a device with single interface in netbox
  hosts: localhost
  connection: local
  collections:
    - netbox.netbox
  vars_files:
    - vars/passwords.yml

  roles:
    - network_settings
    - netbox_new_ip
    - create_dns_from_netbox
