---
- name: Perform maintenance as needed
  hosts: all
  vars_files:
    - vars/passwords.yml
  roles:
    - network_settings
    - migrate_sources
    - pm_cli
    - rsyslog
    - install_promtail
    - role: postfix_internal
      when: inventory_hostname not in groups['tags_mailserver']
    - role: debian_unatt_upg
      when: inventory_hostname in groups['tags_autoupdate']
    - zabbix_inst
    - role: fstrim
      when: inventory_hostname in groups['tags_discard']

  tasks:
    - name: disable NTP on LXC
      service:
        name: ntp
        state: stopped
        enabled: no
      ignore_errors: true
      when: inventory_hostname in groups['tags_LXC']

    - name: Deinstall ntp
      package:
        name: ntp
        state: absent
      when: inventory_hostname in groups['tags_LXC']
