- name: Do local
  hosts: localhost
  connection: local
  collections:
    - netbox.netbox
    - community.general
  vars_files:
    - vars/passwords.yml
  vars:
    vm_cpu: 1
    vm_mem: 1024
    clone_id: 113
    template_name: debian-buster-tmpl
    storage_name: vm_rbd
    new_vm_name: antares
    target_node: alphard

  tasks:

    - name: tweak settings
      community.general.proxmox_kvm:
        api_user: root@pam
        api_password: '{{ proxmox_pass }}'
        api_host: '{{ target_node }}'
        name: '{{ new_vm_name }}'
        node: '{{ target_node }}'
        cores: '{{ vm_cpu }}'
        memory: '{{ vm_mem }}'
        update: true
      register: stuff

    - debug:
        var: stuff

# - name: test far
#   hosts: fizz
#   tasks:
#     - name: hello
#       command: uname -a

#     - name: hello self
#       command: uname -a
#       delegate_to: localhost
