---
- name: Perform maintenance as needed
  hosts: all
  vars_files:
    - vars/passwords.yml
  roles:
    - network_settings

  tasks:

    - name: grab foo
      local_action:
        module: zabbix_host_info
        host_name: 'xxx{{ inventory_hostname_short }}'
        login_password: '{{ zabbix_pw }}'
        login_user: Admin
        server_url: 'http://{{ zabbix_server }}/'
      register: stuff

    - debug:
        var: stuff
