---
domainname: garbled.net
zabbix_server: 'zabbix.{{ domainname }}'
netbox_server: 'http://fafnir.{{ domainname }}'
netbox_vrf: '192.168.10.0/23'
netbox_prefix: '192.168.10.0/23'
timezone: 'America/Phoenix'
patchman_server: beid
patchman_url: 'http://{{ patchman_server }}.{{ domainname }}:3000/patchman'
