---
- name: Download the dark theme
  get_url:
    url: https://raw.githubusercontent.com/Weilbyte/PVEDiscordDark/master/PVEDiscordDark.sh
    dest: /root/PVEDiscordDark.sh
    mode: '0755'

- name: Install theme
  command: /root/PVEDiscordDark.py install
