---
# deletes the entry cur_name
- name: get dns entry
  set_fact:
    cur_ip: "{{ lookup('dig', cur_name) }}"

- name: Print what is going on
  debug:
    var: cur_ip

- name: Delete forward record
  nsupdate:
    key_name: rndc-remote-key
    key_secret: '{{ rndc_remote_key }}'
    key_algorithm: hmac-md5
    server: '{{ dns_list[0] }}'
    zone: '{{ domainname }}'
    record: '{{ cur_name }}'
    state: absent
  delegate_to: localhost
  when: '"NXDOMAIN" not in cur_ip'

- name: Delete reverse record
  nsupdate:
    key_name: rndc-remote-key
    key_secret: '{{ rndc_remote_key }}'
    key_algorithm: hmac-md5
    server: '{{ dns_list[0] }}'
    type: 'PTR'
    #value: '{{ cur_name }}.{{ domainname }}.'
    record: '{{ cur_ip | ipaddr("revdns") }}'
    state: absent
  delegate_to: localhost
  when: '"NXDOMAIN" not in cur_ip'
