---
- name: Install unattended-upgrades
  package:
    name:
      - unattended-upgrades
      - apt-listchanges
      - bsd-mailx

- name: Set random times
  set_fact:
    au_hour: '{{ ["01", "02", "03"] | random }}'
    au_minute: '{{ 60 | random }}'
  when: au_time_random

- name: Set au_auto_reboot
  set_fact:
    au_auto_reboot: 'true'
  when: inventory_hostname in groups['tags_autoreboot']

- name: Install the auto-updates file
  template:
    src: templates/50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: 0644

- name: Install the auto-updates enabler
  template:
    src: files/20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 0644

- name: Create override dirs
  file:
    state: directory
    path: '{{ item }}'
    owner: root
    group: root
    mode: 0755
  with_items:
    - /etc/systemd/system/apt-daily.timer.d
    - /etc/systemd/system/apt-daily-upgrade.timer.d

- name: Install download override
  copy:
    src: files/dl_timer.conf
    dest: /etc/systemd/system/apt-daily.timer.d/override.conf 
    owner: root
    group: root
    mode: 0644

- name: Install upgrade override
  copy:
    src: files/ug_timer.conf
    dest: /etc/systemd/system/apt-daily-upgrade.timer.d/override.conf 
    owner: root
    group: root
    mode: 0644

- name: reload systemd
  systemd:
    daemon_reload: yes
