- name: Set hostname and domain
  cisco.ios.ios_system:
    hostname: '{{ inventory_hostname }}'
    domain_name: '{{ domainname }}'
    name_servers: '{{ dns_list }}'
    lookup_source: Vlan1
    lookup_enabled: yes

- name: Set clock
  cisco.ios.ios_config:
    lines:
      - clock timezone MST -7 0

- name: Set NTP
  cisco.ios.ios_ntp:
    server: '{{ ntp_ip }}'
    source_int: Vlan1
    logging: true
    state: present

- name: Create a napalm user
  cisco.ios.ios_user:
    name: napalm
    configured_password: '{{ napalm_password }}'
    update_password: on_create
    state: present

- name: Set default route
  cisco.ios.ios_config:
    lines:
      - 'ip default-gateway {{ default_gateway }}'

- name: Setup basic snmp
  cisco.ios.ios_config:
    lines:
      - snmp-server community public ro
      - snmp-server contact root@garbled.net
      - snmp-server location Blue Rack, Green Room

- name: Enable LLDP
  cisco.ios.ios_lldp:
    state: present

- name: Configure the VLANs
  cisco.ios.ios_vlans:
    config:
      - vlan_id: '{{ item.value.vid }}'
        name: '{{ item.value.name }}'
  loop: '{{ vlan_list }}'
  when: vlan_list is defined

- name: Configure the LAGs
  cisco.ios.ios_lag_interfaces:
    config: '{{ lagmap }}'
    state: overridden
  when: lagmap is defined

- name: Configure the interfaces
  cisco.ios.ios_interfaces:
    config: '{{ switchmap }}'
    state: overridden
  when: switchmap is defined

- name: Configure the L2 interfaces
  cisco.ios.ios_l2_interfaces:
    config: '{{ l2_switchmap }}'
    state: overridden
  when: l2_switchmap is defined
                    
- name: save config to tftp, then save to device
  cisco.ios.ios_command:
    commands:
      - command: 'copy startup-config tftp://{{ tftp_ip}}/{{ inventory_hostname }}.startup_config'
        prompt: 'Address or name of remote host'
        answer: "\r\r"
      - command: copy running-config startup-config
        prompt: 'Destination filename'
        answer: "\r"
