- name: install deps
  package:
    state: present
    name:
      - python3
      - python3-dev
      - python3-venv
      - python3-pip
      - libffi-dev
      - libssl-dev
      - mosquitto-clients

- name: create i2c just cuz
  group:
    name: i2c

- name: same with gpio
  group:
    name: gpio

- name: create hass user
  user:
    name: hass
    groups:
      - dialout
      - gpio
      - i2c
    shell: /bin/bash
    
- name: create /opt/hass
  file:
    path: /opt/hass
    state: directory
    owner: hass
    group: hass
    mode: 0755

- name: create python3 venv
  pip:
    name:
      - wheel
      - homeassistant
    virtualenv: /opt/hass
    virtualenv_command: pyvenv-3.7
  become: true
  become_user: hass

- name: Create hass init
  copy:
    dest: /etc/systemd/system/hass@hass.service
    owner: root
    group: root
    mode: 0644
    content: |
      [Unit]
      Description=Home Assistant
      After=network-online.target
      [Service]
      Type=simple
      User=%i
      ExecStart=/opt/hass/bin/hass -c "/home/%i/.homeassistant"
      Restart=on-failure
      RestartSec=5s
      [Install]
      WantedBy=multi-user.target

- name: daemon reload and set
  systemd:
    name: hass@hass
    daemon_reload: true
    enabled: true
    state: started
