---
- name: Delete the cdrom lines from apt
  lineinfile:
    path: /etc/apt/sources.list
    state: absent
    regexp: '^deb cdrom'

- name: Force apt to allow releasinfo changes
  command: apt-get update --allow-releaseinfo-change
  args:
    warn: false
    
- name: apt update
  apt:
    update_cache: yes
    upgrade: "yes"

- name: install the minimum stuff
  package:
    name:
      - curl
      - net-tools
      - zabbix-agent
      - qemu-guest-agent
      - tcpdump
      - dnsutils
